"""Template: pin a 1D AERO-S beam to an existing 2D SPARTA outline.

Unlike template_rectangle.py/template_circle.py/template_custom.py, this
does NOT build a gmsh mesh - it takes an already-exported {title}_sparta.txt
(the boundary outline of a thickness-t body, generated by any of the other
templates) and a separately-specified beam centerline, and produces the
AERO-S 1D beam mesh + per-node mapping file needed for the beam-coupling
path (SpartaBeamExchanger / fix_AERO_S_beam on the C++ side).

Edit the SPARTA_SURFACE_FILE/BEAM/MATERIAL sections below, then run:
    python template_beam.py
"""

from beam_export import export_beam_coupled_mesh
from materials import Material

# -----------------------------------------------------------------------------
# SPARTA OUTLINE (already generated by another template)
# -----------------------------------------------------------------------------
SPARTA_SURFACE_FILE = "BEAM_FINAL_QUAD_REV4/BEAM_FINAL_QUAD_REV4_sparta.txt"

TITLE = "beam_coupling_test"
OUT_DIR = TITLE

# -----------------------------------------------------------------------------
# BEAM CENTERLINE
# -----------------------------------------------------------------------------
# Evenly spaced nodes along the span; edit directly for a non-straight beam.
N_BEAM_NODES = 11
SPAN_LENGTH = 1.0
BEAM_POINTS = [(0.0, i * SPAN_LENGTH / (N_BEAM_NODES - 1)) for i in range(N_BEAM_NODES)]

# -----------------------------------------------------------------------------
# MATERIAL (beam section properties - area/ixx/iyy/izz now carry real meaning,
# unlike the 0.0 placeholders used by the 2D shell-mesh writer)
# -----------------------------------------------------------------------------
MATERIALS = [
    Material(
        id=1,
        area=1.0e-4,
        youngs_modulus=1.0e9,
        poisson_ratio=0.0,
        density=1.0e3,
        ixx=1.0e-9,
        iyy=1.0e-9,
        izz=1.0e-9,
    )
]
DEFAULT_MATERIAL_ID = 1

# -----------------------------------------------------------------------------
# BOUNDARY CONDITIONS
# -----------------------------------------------------------------------------
# Cantilever: pin all 6 dofs at the root (beam node index 0), and pin
# out-of-plane dofs (Zdisp=3, Xrot=4, Yrot=5) at every other node to enforce
# strict 2D bending, since SPARTA never produces out-of-plane gap/force in
# this pipeline.
FIXED_DOFS = {0: [1, 2, 3, 4, 5, 6]}
for _i in range(1, N_BEAM_NODES):
    FIXED_DOFS[_i] = [3, 4, 5]

# -----------------------------------------------------------------------------
# EXPORT
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    generated_files = export_beam_coupled_mesh(
        title=TITLE,
        out_dir=OUT_DIR,
        sparta_surface_file=SPARTA_SURFACE_FILE,
        beam_points=BEAM_POINTS,
        materials=MATERIALS,
        default_material_id=DEFAULT_MATERIAL_ID,
        fixed_dofs=FIXED_DOFS,
    )
    for label, path in generated_files.items():
        print(f"{label}: {path}")
